spring:
  datasource:
    username: 'esm'
    password: '123456'
    url: jdbc:postgresql://localhost:15432/db-provider

  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'


    hibernate:
      ddl-auto: 'create-drop'
